- readme.md
<p align="center">
</p>
A _flappy birdish_ game powered by Flame.
It follows a simple goal: Dodge the obstacles in your way and reach the highest score. 
<p align="center">
</p>
> Add flutters to list of games

- contributing.md
- readme.md
Closes #11 
Also fixes the following:
> ✖ Linting
> 
>   readme.md:58:1
>   ✖   1:1  Missing main list heading                    remark-lint:awesome/heading
>   ✖   1:1  Git repository must be at least 30 days old  remark-lint:awesome/git-repo-age
>   ✖  18:1  ToC should not contain section "License"     remark-lint:awesome/toc
>   ✖  45:4  Invalid list item link                       remark-lint:awesome/list-item
>   ✖  50:4  Invalid list item link                       remark-lint:awesome/list-item
>   ✖  55:4  Invalid list item link                       remark-lint:awesome/list-item
>   ✖  58:1  Don’t add a trailing ? to headings           remark-lint:no-heading-punctuation
>   ✖  66:4  Invalid list item link                       remark-lint:awesome/list-item
>   ✖  69:1  Don’t add …
> docs: fix awesome-lint errors

- readme.md
Hey 👋
I've added my 'Four In A Row' board game to the list of published apps. For this, I've created a new category for Board games. Let me know if this is okay.
> Add Four In A Row board game

- readme.md
> Update readme.md and add tower defense genre

- readme.md
After 3 months, 2 translated versions, I finally completed the simplified Chinese version of the Flame basic tutorial! There are quite a lot of game lovers and game developers in China, and I hope that Flame can carry forward in China with good translation!
> Manually translated version of the tutorial (Simplified Chinese)

- readme.md
Added article Flutter Web and Flame in the Readme.md file
> Update readme.md by adding article

- .github/workflows/lint.yml
- contributing.md
- readme.md
Closes #28 
Changes made:
- Make filenames uppercase again (it is up to us according to their guidelines)
- Remove all `Add your item` links and move it to a badge on top
- Center badges under logo (style requirement)
- Fix header formatting in the Plugin section
- Add `By xy` to some entries to have consistent formatting
- Adjust `CONTRIBUTING.md`
- Fixing all other lint errors with `awesome-lint`
Reference: https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md
If possible, please read the reference and check if I didn't miss something.
> Fix formatting for official awesome PR

- README.md
* adding a short description of flame
* make the use of 'by' consistent on entries
Those are the only things that I could see that didn't match (https://github.com/sindresorhus/awesome/pull/1785)
> Fix some rules from awesome awesome

- LICENSE
- README.md
Those are changes made by the awesome maintainer. Chinese translations will be readded in a separate file soon (required)
> style: apply suggested awesome changes

- CONTENT_ZH.md
- README.md
Was removed for the awesome-pr. Now extracted into a separate file according to the guidelines.
> Readd chinese content

- README.md
> feat: add example category

- README.md
Add Tile Paths game to this new created section with Google Play link and the creator's github link.
Thank you for the opportunity to share it here and for all the Flame engine hard work. :)
> Create Puzzle Games Section and Add a game to it.

- README.md
Hey team Flame!
This PR adds my 8 Ball Billiards game that I've posted on Discord earlier, as well as my Air Hockey game which was released before.
- I took over the game categories that the Play Store uses but let me know if they should be adjusted. Air Hockey could fit under casual games as well I guess.
- I've reordered the categories alphabetically as mentioned in the contributing file. Let me know if this is okay as I now unintentionally take up the first two categories under app released 😬
> Add Air Hockey and Pool Ball

- README.md
Added my game Omnichess under the board games section
> added Omnichess

- README.md
Added Flame articles by yayo code.
> Added flame articles by yayocode

- CONTENT_ES.md
- README.md
Added Spanish section and content
> Added Spanish section and content

- README.md
Update links from Yayo code tutorials to point to the new domain.
> Update links from Yayo code tutorials to point to the new domain

- README.md
🥳 
Adding new a new flame game (though basic) to the collection, currently only on Android.
> Add another flame game example to the collection

- README.md
- Adding a new category "Simulation"
- Adding a flame game "Random Race" to the list (available on both Play Store and App Store)
🥳🥳🥳
> Add new category (Simulation) and add app (Random Race)

- README.md
Hey,
I've released Mathonaut two months ago and wanted to share it to you guys. It's all built using Flame 🔥
It's a little platformer in which the player has to collect numbers in order to progress through the game.
Thanks for reading.
> Added an educational game (Mathonaut)

- README.md
Add Jade Rapids game to the list under App Releases > Casual
> Add Jade Rapids

- README.md
Add Escaper: Run to the list under App Releases > Casual
> add Escaper:Run to the list

- README.md
These were already "deprecated"/"outdated" years ago. Now they are relics of the past. Might as well remove the entire section.
> feat: Remove deprecated articles

- README.md
I just added the [Save The Potato](http://savethepotato.com/) game here.
> Add save the potato links

- README.md
> Add Oderrube Game

- README.md
Add Bubble Panic! Game to App Releases list.
> Add Bubble Panic! Game

- README.md
It's this game I made: https://github.com/maurovanetti/guidi-tu
> Sober Driver (open-source game)

- README.md
Adds an app built with Flame to Educational list.
> Adds an app built with Flame to Educational list.

- README.md
Hopefully this game shows what the Flame Engine can do. So much respect for the community 👏
> Add The Darkblade Game
